import type { Language } from "@/lib/i18n";

const copy = {
  fr: {
    tab: "VOS LEVIERS ANTI-ÂGE", title: "Vos leviers anti-âge", intro: "Trois actions personnalisées, classées selon leur potentiel à long terme. Les mois affichés sont des fourchettes issues d’études de cohortes et d’un modèle prudent — ils ne sont ni garantis ni additionnables.",
    gain: "GAIN DE VIE POTENTIEL", months: "mois", objective: "OBJECTIF À VIE", evidence: "REPÈRE SCIENTIFIQUE", confidence: "Niveau de preuve", high: "élevé", medium: "modéré", low: "exploratoire",
    targetTobacco: "Arrêt complet du tabac, avec accompagnement professionnel.", evidenceTobacco: "L’arrêt à 35 ans a été associé à environ 6 à 8,5 années gagnées versus poursuite; un bénéfice persiste à 65 ans.",
    targetActivity: "150–300 min/semaine d’activité modérée + 2 séances de renforcement.", evidenceActivity: "Même 75 min/semaine de marche rapide ont été associés à environ 1,8 année gagnée après 40 ans versus inactivité.",
    targetSedentary: "Moins de 8 h assis/jour et 2–5 min de mouvement toutes les 30–60 min.", evidenceSedentary: "Le bénéfice propre de la réduction de la sédentarité est probable mais moins précisément quantifié que celui de l’activité.",
    targetSleep: "7–9 h/nuit, horaires réguliers et dépistage si ronflement, apnées ou insomnie.", evidenceSleep: "Le sommeil réparateur est associé à une mortalité plus faible; l’estimation en mois reste indirecte.",
    targetNutrition: "≥5 portions de fruits/légumes/jour, légumineuses ≥3/sem., noix ≥5/sem., céréales complètes quotidiennes; limiter boissons sucrées et charcuteries.", evidenceNutrition: "Une consommation adéquate de fruits et légumes a été associée à environ 3,25 années de vie supplémentaires dans une cohorte nationale.",
    targetAlcohol: "Réduire vers 0; à défaut, plusieurs jours sans alcool et éviter les consommations groupées.", evidenceAlcohol: "Le risque augmente avec la dose; la conversion en mois est moins robuste et dépend fortement du niveau initial.",
    targetStress: "10–20 min/jour de récupération active, sommeil protégé et prise en charge si épuisement durable.", evidenceStress: "Le stress et la santé mentale contribuent au risque global, mais leur effet isolé sur l’espérance de vie est difficile à séparer.",
    targetMorphology: "Tour de taille/taille <0,5 si réaliste, avec perte progressive et maintien musculaire.", evidenceMorphology: "Le poids et le tour de taille sont des marqueurs de risque; le bénéfice dépend du profil métabolique et de la méthode utilisée.",
    productEyebrow: "ARKOPHARMA · PRÉVENTION GLOBALE 12", productTitle: "12 actions. Une lecture transparente des doses.", productIntro: "Une formule multi-actifs à positionner comme soutien nutritionnel, sans lui attribuer de gain de longévité démontré chez l’humain.",
    dose: "PAR DOSE JOURNALIÈRE", nutrients: "NUTRIMENTS & % VNR", botanicals: "PHYTO-ACTIFS", caution: "PRUDENCE", cautionText: "Adulte uniquement. Déconseillé grossesse/allaitement, allergie aux Astéracées et avec anticoagulants, antidiabétiques ou antidépresseurs sans avis professionnel.", disclaimer: "Les gains en mois concernent les habitudes de vie, pas le complément. Aucun essai ne démontre que la formule complète allonge la durée de vie humaine."
  },
  en: {
    tab: "YOUR ANTI-AGE LEVERS", title: "Your anti-age levers", intro: "Three personalized actions ranked by long-term potential. Month ranges come from cohort evidence and a conservative model; they are neither guaranteed nor additive.", gain: "POTENTIAL LIFE GAIN", months: "months", objective: "LIFELONG TARGET", evidence: "SCIENTIFIC BENCHMARK", confidence: "Evidence level", high: "high", medium: "moderate", low: "exploratory",
    targetTobacco: "Complete smoking cessation with professional support.", evidenceTobacco: "Stopping at 35 was associated with roughly 6–8.5 years gained versus continuing; benefit remains at 65.", targetActivity: "150–300 min/week moderate activity plus two strength sessions.", evidenceActivity: "Even 75 min/week of brisk walking was associated with about 1.8 years gained after age 40 versus inactivity.", targetSedentary: "Under 8 seated hours/day and 2–5 min movement every 30–60 min.", evidenceSedentary: "The independent benefit of reducing sitting is likely but less precisely quantified than exercise.", targetSleep: "7–9 h/night, regular timing and screening for snoring, apnoea or insomnia.", evidenceSleep: "Restorative sleep is associated with lower mortality; the month estimate remains indirect.", targetNutrition: "≥5 fruit/vegetable servings/day, legumes ≥3/week, nuts ≥5/week, daily whole grains; limit sugary drinks and processed meat.", evidenceNutrition: "Adequate fruit and vegetable intake was associated with about 3.25 extra years in a nationwide cohort.", targetAlcohol: "Move toward zero; otherwise include alcohol-free days and avoid binges.", evidenceAlcohol: "Risk rises with dose; translation into months is less robust and depends on baseline intake.", targetStress: "10–20 min/day active recovery, protected sleep and care for persistent exhaustion.", evidenceStress: "Stress and mental health contribute to overall risk, but their isolated lifespan effect is difficult to separate.", targetMorphology: "Waist-to-height ratio below 0.5 where realistic, with gradual fat loss and muscle preservation.", evidenceMorphology: "Weight and waist are risk markers; benefit depends on metabolic profile and method.", productEyebrow: "ARKOPHARMA · GLOBAL PREVENTION 12", productTitle: "12 actions. A transparent view of every dose.", productIntro: "A multi-active formula to position as nutritional support, without claiming proven human lifespan extension.", dose: "PER DAILY DOSE", nutrients: "NUTRIENTS & % NRV", botanicals: "BOTANICAL ACTIVES", caution: "CAUTION", cautionText: "Adults only. Not for pregnancy/breastfeeding, Asteraceae allergy, or use with anticoagulants, antidiabetics or antidepressants without professional advice.", disclaimer: "Month gains relate to lifestyle habits, not the supplement. No trial shows that the complete formula extends human lifespan."
  },
  it: {
    tab: "LE TUE LEVE ANTI-ETÀ", title: "Le tue leve anti-età", intro: "Tre azioni personalizzate ordinate per potenziale a lungo termine. Gli intervalli in mesi derivano da coorti e da un modello prudente; non sono garantiti né sommabili.", gain: "GUADAGNO DI VITA POTENZIALE", months: "mesi", objective: "OBIETTIVO A VITA", evidence: "RIFERIMENTO SCIENTIFICO", confidence: "Livello di evidenza", high: "alto", medium: "moderato", low: "esplorativo",
    targetTobacco: "Cessazione completa del fumo con supporto professionale.", evidenceTobacco: "Smettere a 35 anni è stato associato a circa 6–8,5 anni guadagnati rispetto a continuare; il beneficio persiste a 65 anni.", targetActivity: "150–300 min/settimana di attività moderata più due sedute di forza.", evidenceActivity: "Anche 75 min/settimana di cammino veloce sono stati associati a circa 1,8 anni guadagnati dopo i 40 anni.", targetSedentary: "Meno di 8 ore seduti/giorno e 2–5 min di movimento ogni 30–60 min.", evidenceSedentary: "Il beneficio indipendente della riduzione della sedentarietà è probabile ma meno precisamente quantificato.", targetSleep: "7–9 ore/notte, orari regolari e screening per russamento, apnee o insonnia.", evidenceSleep: "Il sonno ristoratore è associato a minore mortalità; la stima in mesi resta indiretta.", targetNutrition: "≥5 porzioni di frutta/verdura al giorno, legumi ≥3/settimana, frutta secca ≥5/settimana, cereali integrali ogni giorno.", evidenceNutrition: "Un apporto adeguato di frutta e verdura è stato associato a circa 3,25 anni in più in una coorte nazionale.", targetAlcohol: "Ridurre verso zero; in alternativa, giorni senza alcol ed evitare abbuffate alcoliche.", evidenceAlcohol: "Il rischio cresce con la dose; la conversione in mesi è meno robusta.", targetStress: "10–20 min/giorno di recupero attivo, sonno protetto e assistenza se l’esaurimento persiste.", evidenceStress: "Stress e salute mentale contribuiscono al rischio globale, ma l’effetto isolato è difficile da separare.", targetMorphology: "Rapporto vita/altezza <0,5 quando realistico, con perdita graduale e mantenimento muscolare.", evidenceMorphology: "Peso e girovita sono marcatori di rischio; il beneficio dipende dal profilo metabolico.", productEyebrow: "ARKOPHARMA · PREVENZIONE GLOBALE 12", productTitle: "12 azioni. Dosi presentate con trasparenza.", productIntro: "Formula multi-attivo da presentare come supporto nutrizionale, senza attribuirle un prolungamento della vita dimostrato.", dose: "PER DOSE GIORNALIERA", nutrients: "NUTRIENTI & % VNR", botanicals: "FITOCOMPLESSI", caution: "PRUDENZA", cautionText: "Solo adulti. Sconsigliato in gravidanza/allattamento, allergia alle Asteraceae o con anticoagulanti, antidiabetici o antidepressivi senza parere professionale.", disclaimer: "I mesi guadagnati riguardano le abitudini, non l’integratore. Nessuno studio dimostra che la formula completa prolunghi la vita umana."
  },
  de: {
    tab: "IHRE ANTI-AGING-HEBEL", title: "Ihre Anti-Aging-Hebel", intro: "Drei personalisierte Maßnahmen nach langfristigem Potenzial. Die Monatsbereiche stammen aus Kohorten und einem vorsichtigen Modell; sie sind weder garantiert noch addierbar.", gain: "POTENZIELLER LEBENSZEITGEWINN", months: "Monate", objective: "LANGFRISTIGES ZIEL", evidence: "WISSENSCHAFTLICHER RICHTWERT", confidence: "Evidenzniveau", high: "hoch", medium: "moderat", low: "explorativ",
    targetTobacco: "Vollständiger Rauchstopp mit professioneller Unterstützung.", evidenceTobacco: "Ein Rauchstopp mit 35 war gegenüber Weiterrauchen mit etwa 6–8,5 gewonnenen Jahren verbunden; Nutzen besteht auch mit 65.", targetActivity: "150–300 Min./Woche moderate Aktivität plus zwei Krafteinheiten.", evidenceActivity: "Schon 75 Min./Woche zügiges Gehen waren ab 40 mit etwa 1,8 gewonnenen Jahren verbunden.", targetSedentary: "Unter 8 Sitzstunden/Tag und alle 30–60 Min. 2–5 Min. Bewegung.", evidenceSedentary: "Der eigenständige Nutzen geringerer Sitzzeit ist wahrscheinlich, aber weniger präzise quantifiziert.", targetSleep: "7–9 Std./Nacht, regelmäßige Zeiten und Abklärung bei Schnarchen, Apnoe oder Insomnie.", evidenceSleep: "Erholsamer Schlaf ist mit geringerer Sterblichkeit verbunden; die Monatsangabe bleibt indirekt.", targetNutrition: "≥5 Portionen Obst/Gemüse täglich, Hülsenfrüchte ≥3/Woche, Nüsse ≥5/Woche, täglich Vollkorn.", evidenceNutrition: "Ausreichend Obst und Gemüse war in einer nationalen Kohorte mit etwa 3,25 zusätzlichen Jahren verbunden.", targetAlcohol: "Richtung null reduzieren; sonst alkoholfreie Tage und kein Rauschtrinken.", evidenceAlcohol: "Das Risiko steigt mit der Dosis; die Umrechnung in Monate ist weniger belastbar.", targetStress: "10–20 Min./Tag aktive Erholung, geschützter Schlaf und Hilfe bei anhaltender Erschöpfung.", evidenceStress: "Stress und psychische Gesundheit tragen zum Gesamtrisiko bei, der isolierte Effekt ist schwer zu trennen.", targetMorphology: "Taille-zu-Größe <0,5, wenn realistisch, mit langsamem Fettverlust und Muskelerhalt.", evidenceMorphology: "Gewicht und Taille sind Risikomarker; der Nutzen hängt vom Stoffwechselprofil ab.", productEyebrow: "ARKOPHARMA · GLOBALPRÄVENTION 12", productTitle: "12 Wirkfelder. Jede Dosis transparent.", productIntro: "Eine Multi-Aktiv-Formel als Ernährungsunterstützung — ohne behauptete Verlängerung der menschlichen Lebensspanne.", dose: "PRO TAGESDOSIS", nutrients: "NÄHRSTOFFE & % NRV", botanicals: "PFLANZENAKTIVE", caution: "VORSICHT", cautionText: "Nur für Erwachsene. Nicht bei Schwangerschaft/Stillzeit, Asteraceae-Allergie oder mit Antikoagulanzien, Antidiabetika oder Antidepressiva ohne fachlichen Rat.", disclaimer: "Die Monatsgewinne beziehen sich auf Lebensgewohnheiten, nicht auf das Produkt. Kein Versuch zeigt, dass die Gesamtformel die menschliche Lebensdauer verlängert."
  }
} as const;

export function antiAgeCopy(language: Language, key: string): string {
  const dictionary = copy[language] as Record<string, string>;
  return dictionary[key] || (copy.fr as Record<string, string>)[key] || key;
}
