export type Language = "fr" | "en" | "it" | "de";

export const languageOptions: Array<{ value: Language; label: string }> = [
  { value: "fr", label: "Français" },
  { value: "en", label: "English" },
  { value: "it", label: "Italiano" },
  { value: "de", label: "Deutsch" }
];

const fr: Record<string, string> = {
  appName: "Âge biologique",
  eyebrow: "Bilan longévité",
  heroTitle: "Estimez votre âge biologique à partir de votre mode de vie.",
  heroText: "Un bilan autonome centré sur les habitudes modifiables : activité, sédentarité, sommeil, stress, nutrition, tabac, alcool et mesures optionnelles.",
  language: "Langue", save: "Enregistrer le bilan", saved: "Bilan enregistré", reset: "Réinitialiser", result: "Résultat estimé",
  biologicalAge: "Âge biologique", chronologicalAge: "Âge chronologique", difference: "Écart estimé", score: "Score global", confidence: "Confiance",
  years: "ans", months: "mois", younger: "plus jeune", older: "plus âgé", sameAge: "proche de l’âge chronologique",
  confidenceLow: "faible", confidenceMedium: "moyenne", confidenceGood: "bonne", profileTitle: "Profil minimal", profileText: "Les données restent dans votre navigateur.",
  age: "Âge", height: "Taille", weight: "Poids", waist: "Tour de taille", optional: "optionnel", movementTitle: "Activité et sédentarité",
  recoveryTitle: "Sommeil et récupération", nutritionTitle: "Nutrition longévité", habitsTitle: "Habitudes générales", vitalsTitle: "Mesures santé optionnelles",
  sportType: "Sport principal", moderateMinutes: "Minutes modérées / semaine", vigorousMinutes: "Minutes intenses / semaine", strengthSessions: "Renforcement / semaine",
  mobilitySessions: "Mobilité / semaine", sittingHours: "Heures assis / jour", sportYears: "Années de pratique régulière", socialPractice: "Pratique sociale", injuries: "Blessures ou limitations",
  sleepHours: "Sommeil / nuit", sleepQuality: "Qualité du sommeil", stressLevel: "Stress perçu, de 0 à 10", fatigueLevel: "Fatigue, de 0 à 10",
  energyStability: "Énergie dans la journée", emotionalEating: "Envies alimentaires liées au stress", fruitVegServingsPerDay: "Fruits et légumes / jour",
  legumesPerWeek: "Légumineuses / semaine", wholeGrains: "Céréales complètes", ultraProcessed: "Aliments ultra-transformés", sugaryDrinksPerWeek: "Boissons sucrées / semaine",
  proteinAtMeals: "Protéines aux repas", nutsSeedsPerWeek: "Noix et graines / semaine", fattyFishPerWeek: "Poisson gras / semaine", processedMeatPerWeek: "Viandes transformées / semaine",
  appetiteChange: "Appétit diminué récemment", unintentionalWeightLoss: "Perte de poids non voulue", tobacco: "Tabac ou nicotine", alcoholDrinksPerWeek: "Verres d’alcool / semaine",
  systolic: "Tension systolique", diastolic: "Tension diastolique", restingHeartRate: "Fréquence cardiaque au repos", breakdownTitle: "Détail du score",
  favorableTitle: "Facteurs favorables", watchTitle: "Facteurs à surveiller", noneReported: "Aucun signal majeur avec les réponses actuelles.", methodTitle: "Méthode et limites",
  methodText: "Cette estimation repose sur un score comportemental fondé sur les habitudes de vie déclarées. Elle ne mesure pas des biomarqueurs et ne constitue pas un diagnostic médical. Toute perte de poids involontaire, fatigue inhabituelle ou mesure anormale doit être discutée avec un professionnel de santé.",
  componentNutrition: "Nutrition", componentActivity: "Activité physique", componentSedentary: "Sédentarité", componentSleep: "Sommeil", componentStressRecovery: "Stress et fatigue",
  componentTobacco: "Tabac et nicotine", componentAlcohol: "Alcool", componentMorphology: "Morphologie", componentVitals: "Mesures santé",
  factorRegularActivity: "activité physique régulière", factorProtectiveNutrition: "habitudes alimentaires protectrices", factorLowTobaccoExposure: "faible exposition au tabac ou à la nicotine",
  factorHighSedentaryTime: "sédentarité élevée", factorTobaccoOrNicotine: "tabac ou nicotine", factorPoorSleep: "sommeil insuffisant ou de mauvaise qualité",
  factorFrequentUltraProcessed: "aliments ultra-transformés fréquents", factorHighAlcohol: "consommation d’alcool élevée", factorHighFatigue: "fatigue élevée", factorIntenseStress: "stress intense",
  factorAppetiteOrWeightChange: "appétit ou poids à surveiller", sportNone: "Aucun sport structuré", sportWalking: "Marche rapide ou randonnée", sportRunning: "Course à pied",
  sportCycling: "Vélo", sportSwimming: "Natation", sportRacket: "Sport de raquette", sportTeam: "Sport collectif", sportStrength: "Musculation", sportFitness: "Fitness ou danse",
  sportYoga: "Yoga, pilates ou mobilité", sportOther: "Autre", socialSolo: "Plutôt seul", socialPair: "À deux", socialGroup: "En groupe", socialClub: "Club ou compétition",
  injuryNone: "Aucune gêne", injuryLight: "Douleurs légères", injuryFrequent: "Blessures fréquentes", injuryLimited: "Pratique limitée", sleepGood: "Bonne", sleepAverage: "Moyenne", sleepPoor: "Mauvaise",
  tobaccoNever: "Jamais", tobaccoFormer: "Ancien fumeur", tobaccoNicotine: "Vape ou nicotine", tobaccoCurrent: "Fumeur actuel", frequencyRare: "Rarement", frequencySome: "Parfois",
  frequencyFrequent: "Souvent", frequencyDaily: "Tous les jours", energyStable: "Plutôt stable", energyVariable: "Variable", energyCrash: "Coups de barre fréquents", energyUnknown: "Je ne sais pas",
  changeNone: "Non", changeSlight: "Un peu", changeClear: "Oui, clairement", changeUnknown: "Je ne sais pas",
  prioritiesTab: "Priorités longévité", prioritiesTitle: "Vos 3 leviers prioritaires", prioritiesIntro: "Classement personnalisé selon l’écart à l’objectif, l’importance du facteur et les réponses au questionnaire.",
  prioritiesEmpty: "Aucune priorité forte n’émerge. Continuez à consolider vos habitudes.", priorityImpact: "Impact potentiel", priorityAction: "Action concrète", priorityWhy: "Pourquoi",
  priorityTobaccoTitle: "Réduire puis arrêter le tabac ou la nicotine", priorityTobaccoAction: "Fixez une date d’arrêt et demandez un accompagnement médical ou pharmaceutique.", priorityTobaccoRationale: "L’exposition au tabac reste un facteur majeur et modifiable de mortalité prématurée.",
  priorityActivityTitle: "Augmenter l’activité physique", priorityActivityAction: "Visez progressivement 150 à 300 minutes d’activité modérée par semaine et 2 séances de renforcement.", priorityActivityRationale: "L’activité régulière soutient la santé cardiovasculaire, métabolique, musculaire et cognitive.",
  prioritySedentaryTitle: "Réduire le temps assis", prioritySedentaryAction: "Interrompez les périodes assises toutes les 30 à 60 minutes et ajoutez de courtes marches.", prioritySedentaryRationale: "Un temps assis élevé reste défavorable même chez les personnes qui font du sport.",
  prioritySleepTitle: "Améliorer le sommeil", prioritySleepAction: "Stabilisez les horaires, visez 7 à 9 heures et consultez en cas de ronflements, apnées ou insomnie persistante.", prioritySleepRationale: "Le sommeil influence la récupération, le métabolisme, l’immunité et les fonctions cognitives.",
  priorityNutritionTitle: "Renforcer la qualité alimentaire", priorityNutritionAction: "Augmentez légumes, fruits, légumineuses, céréales complètes, noix et poisson, tout en réduisant ultra-transformés et viandes transformées.", priorityNutritionRationale: "Les régimes riches en végétaux et peu transformés sont associés à de meilleurs résultats cardiométaboliques.",
  priorityAlcoholTitle: "Réduire l’alcool", priorityAlcoholAction: "Diminuez progressivement le nombre de verres et prévoyez plusieurs jours sans alcool chaque semaine.", priorityAlcoholRationale: "Le risque sanitaire augmente avec la consommation ; moins est généralement préférable.",
  priorityStressTitle: "Agir sur stress et fatigue", priorityStressAction: "Programmez une récupération quotidienne, protégez le sommeil et consultez si l’épuisement persiste.", priorityStressRationale: "Le stress chronique et la fatigue peuvent dégrader les comportements de santé et la qualité de vie.",
  priorityMorphologyTitle: "Améliorer la santé métabolique", priorityMorphologyAction: "Privilégiez des changements progressifs d’alimentation, d’activité et de renforcement plutôt qu’un objectif de poids rapide.", priorityMorphologyRationale: "La composition corporelle et le tour de taille sont des marqueurs utiles du risque métabolique.",
  supplementTitle: "Complément Arkopharma Longévité 12", supplementIntro: "Information produit et niveau de prudence — ce bloc ne recommande pas une prise systématique.",
  supplementComposition: "Principaux actifs", supplementCompositionText: "Fibres de chicorée, acérola, ginseng rouge, gingembre, quercétine, ginkgo, scutellaire, SOD de melon, vitamines C, B3, D3, E et A, magnésium, zinc et sélénium.",
  supplementEvidence: "Lecture des preuves", supplementEvidenceText: "Les vitamines et minéraux corrigent surtout un apport insuffisant ou une carence. Les preuves directes d’un allongement de la vie chez l’humain pour cette formule complète ne sont pas établies.",
  supplementCaution: "Précautions importantes", supplementCautionText: "Réservé à l’adulte. Ne pas utiliser pendant la grossesse ou l’allaitement, ni sans avis professionnel en cas de traitement anticoagulant, antidiabétique ou antidépresseur. Vérifiez aussi les autres apports de vitamine D et A.",
  supplementRule: "Un complément ne remplace ni une alimentation variée, ni l’activité physique, ni le sommeil, ni le suivi médical."
};

const en: Record<string, string> = {
  ...fr,
  appName: "Biological age", eyebrow: "Longevity assessment", heroTitle: "Estimate your biological age from your lifestyle.", heroText: "A standalone assessment focused on modifiable habits: activity, sedentary time, sleep, stress, nutrition, tobacco, alcohol and optional health measurements.",
  language: "Language", save: "Save assessment", saved: "Assessment saved", reset: "Reset", result: "Estimated result", biologicalAge: "Biological age", chronologicalAge: "Chronological age", difference: "Estimated difference", score: "Overall score", confidence: "Confidence",
  years: "years", months: "months", younger: "younger", older: "older", sameAge: "close to chronological age", confidenceLow: "low", confidenceMedium: "medium", confidenceGood: "good",
  profileTitle: "Minimal profile", profileText: "Your data stays in your browser.", age: "Age", height: "Height", weight: "Weight", waist: "Waist circumference", optional: "optional",
  movementTitle: "Activity and sedentary time", recoveryTitle: "Sleep and recovery", nutritionTitle: "Longevity nutrition", habitsTitle: "General habits", vitalsTitle: "Optional health measurements",
  sportType: "Main sport", moderateMinutes: "Moderate minutes / week", vigorousMinutes: "Vigorous minutes / week", strengthSessions: "Strength sessions / week", mobilitySessions: "Mobility sessions / week", sittingHours: "Sitting hours / day", sportYears: "Years of regular practice", socialPractice: "Social practice", injuries: "Injuries or limitations",
  sleepHours: "Sleep / night", sleepQuality: "Sleep quality", stressLevel: "Perceived stress, 0 to 10", fatigueLevel: "Fatigue, 0 to 10", energyStability: "Daytime energy", emotionalEating: "Stress-related food cravings",
  fruitVegServingsPerDay: "Fruit and vegetables / day", legumesPerWeek: "Legumes / week", wholeGrains: "Whole grains", ultraProcessed: "Ultra-processed foods", sugaryDrinksPerWeek: "Sugary drinks / week", proteinAtMeals: "Protein at meals", nutsSeedsPerWeek: "Nuts and seeds / week", fattyFishPerWeek: "Fatty fish / week", processedMeatPerWeek: "Processed meat / week", appetiteChange: "Recent appetite decrease", unintentionalWeightLoss: "Unintentional weight loss", tobacco: "Tobacco or nicotine", alcoholDrinksPerWeek: "Alcoholic drinks / week", systolic: "Systolic blood pressure", diastolic: "Diastolic blood pressure", restingHeartRate: "Resting heart rate",
  breakdownTitle: "Score breakdown", favorableTitle: "Favorable factors", watchTitle: "Factors to watch", noneReported: "No major signal with the current answers.", methodTitle: "Method and limitations", methodText: "This estimate is based on a behavioral score derived from self-reported lifestyle habits. It does not measure biomarkers and is not a medical diagnosis. Unintentional weight loss, unusual fatigue or abnormal measurements should be discussed with a healthcare professional.",
  componentNutrition: "Nutrition", componentActivity: "Physical activity", componentSedentary: "Sedentary time", componentSleep: "Sleep", componentStressRecovery: "Stress and fatigue", componentTobacco: "Tobacco and nicotine", componentAlcohol: "Alcohol", componentMorphology: "Body composition", componentVitals: "Health measurements",
  factorRegularActivity: "regular physical activity", factorProtectiveNutrition: "protective eating habits", factorLowTobaccoExposure: "low tobacco or nicotine exposure", factorHighSedentaryTime: "high sedentary time", factorTobaccoOrNicotine: "tobacco or nicotine use", factorPoorSleep: "insufficient or poor-quality sleep", factorFrequentUltraProcessed: "frequent ultra-processed foods", factorHighAlcohol: "high alcohol intake", factorHighFatigue: "high fatigue", factorIntenseStress: "intense stress", factorAppetiteOrWeightChange: "appetite or weight change to monitor",
  sportNone: "No structured sport", sportWalking: "Brisk walking or hiking", sportRunning: "Running", sportCycling: "Cycling", sportSwimming: "Swimming", sportRacket: "Racket sport", sportTeam: "Team sport", sportStrength: "Strength training", sportFitness: "Fitness or dance", sportYoga: "Yoga, pilates or mobility", sportOther: "Other", socialSolo: "Mostly alone", socialPair: "With one other person", socialGroup: "In a group", socialClub: "Club or competition", injuryNone: "No limitation", injuryLight: "Mild pain", injuryFrequent: "Frequent injuries", injuryLimited: "Practice is limited", sleepGood: "Good", sleepAverage: "Average", sleepPoor: "Poor", tobaccoNever: "Never", tobaccoFormer: "Former smoker", tobaccoNicotine: "Vape or nicotine", tobaccoCurrent: "Current smoker", frequencyRare: "Rarely", frequencySome: "Sometimes", frequencyFrequent: "Often", frequencyDaily: "Every day", energyStable: "Mostly stable", energyVariable: "Variable", energyCrash: "Frequent energy crashes", energyUnknown: "I do not know", changeNone: "No", changeSlight: "A little", changeClear: "Yes, clearly", changeUnknown: "I do not know",
  prioritiesTab: "Longevity priorities", prioritiesTitle: "Your 3 priority levers", prioritiesIntro: "Personalized ranking based on the gap to target, the importance of each factor and your questionnaire answers.", prioritiesEmpty: "No strong priority emerges. Keep consolidating your habits.", priorityImpact: "Potential impact", priorityAction: "Practical action", priorityWhy: "Why",
  priorityTobaccoTitle: "Reduce and stop tobacco or nicotine", priorityTobaccoAction: "Set a quit date and seek medical or pharmacy support.", priorityTobaccoRationale: "Tobacco exposure remains a major and modifiable cause of premature mortality.", priorityActivityTitle: "Increase physical activity", priorityActivityAction: "Progress toward 150–300 minutes of moderate activity per week plus two strength sessions.", priorityActivityRationale: "Regular activity supports cardiovascular, metabolic, muscular and cognitive health.", prioritySedentaryTitle: "Reduce sitting time", prioritySedentaryAction: "Break up sitting every 30–60 minutes and add short walks.", prioritySedentaryRationale: "High sedentary time remains unfavorable even in people who exercise.", prioritySleepTitle: "Improve sleep", prioritySleepAction: "Keep regular times, aim for 7–9 hours and seek advice for persistent insomnia, snoring or suspected apnoea.", prioritySleepRationale: "Sleep affects recovery, metabolism, immunity and cognitive function.", priorityNutritionTitle: "Improve diet quality", priorityNutritionAction: "Increase vegetables, fruit, legumes, whole grains, nuts and fish while reducing ultra-processed and processed meats.", priorityNutritionRationale: "Plant-rich, minimally processed dietary patterns are associated with better cardiometabolic outcomes.", priorityAlcoholTitle: "Reduce alcohol", priorityAlcoholAction: "Gradually reduce drinks and schedule several alcohol-free days each week.", priorityAlcoholRationale: "Health risk rises with intake; less is generally better.", priorityStressTitle: "Address stress and fatigue", priorityStressAction: "Schedule daily recovery, protect sleep and seek help if exhaustion persists.", priorityStressRationale: "Chronic stress and fatigue can worsen health behaviours and quality of life.", priorityMorphologyTitle: "Improve metabolic health", priorityMorphologyAction: "Choose gradual food, activity and strength changes rather than rapid weight-loss targets.", priorityMorphologyRationale: "Body composition and waist size are useful markers of metabolic risk.",
  supplementTitle: "Arkopharma Longevity 12 supplement", supplementIntro: "Product information and caution level — this section does not recommend routine use.", supplementComposition: "Main ingredients", supplementCompositionText: "Chicory fibres, acerola, red ginseng, ginger, quercetin, ginkgo, skullcap, melon SOD, vitamins C, B3, D3, E and A, magnesium, zinc and selenium.", supplementEvidence: "Evidence overview", supplementEvidenceText: "Vitamins and minerals mainly help when intake is insufficient or a deficiency is present. Direct evidence that this complete formula extends human lifespan has not been established.", supplementCaution: "Important precautions", supplementCautionText: "Adults only. Do not use during pregnancy or breastfeeding, or without professional advice with anticoagulant, antidiabetic or antidepressant treatment. Also check other vitamin D and A intakes.", supplementRule: "A supplement does not replace a varied diet, physical activity, sleep or medical care."
};

const it: Record<string, string> = {
  ...en,
  appName: "Età biologica", eyebrow: "Valutazione della longevità", heroTitle: "Stima la tua età biologica in base allo stile di vita.", heroText: "Una valutazione autonoma delle abitudini modificabili: attività, sedentarietà, sonno, stress, alimentazione, tabacco, alcol e misure sanitarie facoltative.", language: "Lingua", save: "Salva valutazione", saved: "Valutazione salvata", reset: "Reimposta", result: "Risultato stimato", biologicalAge: "Età biologica", chronologicalAge: "Età cronologica", difference: "Differenza stimata", score: "Punteggio globale", confidence: "Affidabilità", years: "anni", months: "mesi", younger: "più giovane", older: "più anziano", sameAge: "vicino all’età cronologica", confidenceLow: "bassa", confidenceMedium: "media", confidenceGood: "buona",
  profileTitle: "Profilo minimo", profileText: "I dati restano nel browser.", age: "Età", height: "Altezza", weight: "Peso", waist: "Circonferenza vita", optional: "facoltativo", movementTitle: "Attività e sedentarietà", recoveryTitle: "Sonno e recupero", nutritionTitle: "Alimentazione per la longevità", habitsTitle: "Abitudini generali", vitalsTitle: "Misure sanitarie facoltative", sportType: "Sport principale", moderateMinutes: "Minuti moderati / settimana", vigorousMinutes: "Minuti intensi / settimana", strengthSessions: "Forza / settimana", mobilitySessions: "Mobilità / settimana", sittingHours: "Ore seduti / giorno", sportYears: "Anni di pratica regolare", socialPractice: "Pratica sociale", injuries: "Infortuni o limitazioni", sleepHours: "Sonno / notte", sleepQuality: "Qualità del sonno", stressLevel: "Stress percepito, da 0 a 10", fatigueLevel: "Stanchezza, da 0 a 10", energyStability: "Energia durante il giorno", emotionalEating: "Desideri alimentari legati allo stress", fruitVegServingsPerDay: "Frutta e verdura / giorno", legumesPerWeek: "Legumi / settimana", wholeGrains: "Cereali integrali", ultraProcessed: "Alimenti ultra-processati", sugaryDrinksPerWeek: "Bevande zuccherate / settimana", proteinAtMeals: "Proteine ai pasti", nutsSeedsPerWeek: "Frutta secca e semi / settimana", fattyFishPerWeek: "Pesce grasso / settimana", processedMeatPerWeek: "Carni lavorate / settimana", appetiteChange: "Calo recente dell’appetito", unintentionalWeightLoss: "Perdita di peso involontaria", tobacco: "Tabacco o nicotina", alcoholDrinksPerWeek: "Bevande alcoliche / settimana", systolic: "Pressione sistolica", diastolic: "Pressione diastolica", restingHeartRate: "Frequenza cardiaca a riposo", breakdownTitle: "Dettaglio del punteggio", favorableTitle: "Fattori favorevoli", watchTitle: "Fattori da monitorare", noneReported: "Nessun segnale importante con le risposte attuali.", methodTitle: "Metodo e limiti", methodText: "Questa stima usa un punteggio comportamentale basato sulle abitudini dichiarate. Non misura biomarcatori e non costituisce una diagnosi medica. Perdita di peso involontaria, stanchezza insolita o valori anomali vanno discussi con un professionista sanitario.",
  componentActivity: "Attività fisica", componentSedentary: "Sedentarietà", componentSleep: "Sonno", componentStressRecovery: "Stress e stanchezza", componentTobacco: "Tabacco e nicotina", componentAlcohol: "Alcol", componentMorphology: "Composizione corporea", componentVitals: "Misure sanitarie", factorRegularActivity: "attività fisica regolare", factorProtectiveNutrition: "abitudini alimentari protettive", factorLowTobaccoExposure: "bassa esposizione a tabacco o nicotina", factorHighSedentaryTime: "sedentarietà elevata", factorTobaccoOrNicotine: "uso di tabacco o nicotina", factorPoorSleep: "sonno insufficiente o di scarsa qualità", factorFrequentUltraProcessed: "consumo frequente di alimenti ultra-processati", factorHighAlcohol: "consumo elevato di alcol", factorHighFatigue: "stanchezza elevata", factorIntenseStress: "stress intenso", factorAppetiteOrWeightChange: "variazioni di appetito o peso da monitorare",
  prioritiesTab: "Priorità longevità", prioritiesTitle: "Le tue 3 leve prioritarie", prioritiesIntro: "Classifica personalizzata in base alla distanza dall’obiettivo, all’importanza del fattore e alle risposte.", prioritiesEmpty: "Non emerge una priorità forte. Continua a consolidare le tue abitudini.", priorityImpact: "Impatto potenziale", priorityAction: "Azione concreta", priorityWhy: "Perché",
  priorityTobaccoTitle: "Ridurre e smettere tabacco o nicotina", priorityTobaccoAction: "Fissa una data e chiedi supporto medico o in farmacia.", priorityTobaccoRationale: "L’esposizione al tabacco resta una causa importante e modificabile di mortalità prematura.", priorityActivityTitle: "Aumentare l’attività fisica", priorityActivityAction: "Progredisci verso 150–300 minuti di attività moderata e due sedute di forza a settimana.", priorityActivityRationale: "L’attività regolare sostiene salute cardiovascolare, metabolica, muscolare e cognitiva.", prioritySedentaryTitle: "Ridurre il tempo seduti", prioritySedentaryAction: "Interrompi la posizione seduta ogni 30–60 minuti e aggiungi brevi camminate.", prioritySedentaryRationale: "Molte ore seduti restano sfavorevoli anche per chi pratica sport.", prioritySleepTitle: "Migliorare il sonno", prioritySleepAction: "Mantieni orari regolari, punta a 7–9 ore e consulta un professionista per insonnia, russamento o apnee sospette.", prioritySleepRationale: "Il sonno influenza recupero, metabolismo, immunità e funzioni cognitive.", priorityNutritionTitle: "Migliorare la qualità alimentare", priorityNutritionAction: "Aumenta verdura, frutta, legumi, cereali integrali, frutta secca e pesce, riducendo ultra-processati e carni lavorate.", priorityNutritionRationale: "Modelli alimentari ricchi di vegetali e poco processati sono associati a migliori esiti cardiometabolici.", priorityAlcoholTitle: "Ridurre l’alcol", priorityAlcoholAction: "Riduci gradualmente i bicchieri e programma più giorni senza alcol ogni settimana.", priorityAlcoholRationale: "Il rischio sanitario cresce con il consumo; meno è generalmente meglio.", priorityStressTitle: "Agire su stress e stanchezza", priorityStressAction: "Programma recupero quotidiano, proteggi il sonno e chiedi aiuto se l’esaurimento persiste.", priorityStressRationale: "Stress cronico e stanchezza possono peggiorare comportamenti di salute e qualità di vita.", priorityMorphologyTitle: "Migliorare la salute metabolica", priorityMorphologyAction: "Preferisci cambiamenti graduali di alimentazione, attività e forza a obiettivi rapidi di peso.", priorityMorphologyRationale: "Composizione corporea e circonferenza vita sono indicatori utili del rischio metabolico.",
  supplementTitle: "Integratore Arkopharma Longevità 12", supplementIntro: "Informazioni sul prodotto e prudenza — questa sezione non raccomanda l’uso sistematico.", supplementComposition: "Principali ingredienti", supplementCompositionText: "Fibre di cicoria, acerola, ginseng rosso, zenzero, quercetina, ginkgo, scutellaria, SOD di melone, vitamine C, B3, D3, E e A, magnesio, zinco e selenio.", supplementEvidence: "Sintesi delle prove", supplementEvidenceText: "Vitamine e minerali aiutano soprattutto in caso di apporto insufficiente o carenza. Non è dimostrato che la formula completa prolunghi la vita umana.", supplementCaution: "Precauzioni importanti", supplementCautionText: "Solo per adulti. Non usare in gravidanza o allattamento, né senza parere professionale con anticoagulanti, antidiabetici o antidepressivi. Controllare anche gli altri apporti di vitamina D e A.", supplementRule: "Un integratore non sostituisce dieta varia, attività fisica, sonno o assistenza medica."
};

const de: Record<string, string> = {
  ...en,
  appName: "Biologisches Alter", eyebrow: "Langlebigkeits-Check", heroTitle: "Schätzen Sie Ihr biologisches Alter anhand Ihres Lebensstils.", heroText: "Eine eigenständige Bewertung veränderbarer Gewohnheiten: Aktivität, Sitzen, Schlaf, Stress, Ernährung, Tabak, Alkohol und optionale Gesundheitswerte.", language: "Sprache", save: "Bewertung speichern", saved: "Bewertung gespeichert", reset: "Zurücksetzen", result: "Geschätztes Ergebnis", biologicalAge: "Biologisches Alter", chronologicalAge: "Chronologisches Alter", difference: "Geschätzte Abweichung", score: "Gesamtpunktzahl", confidence: "Aussagekraft", years: "Jahre", months: "Monate", younger: "jünger", older: "älter", sameAge: "nahe am chronologischen Alter", confidenceLow: "gering", confidenceMedium: "mittel", confidenceGood: "gut",
  profileTitle: "Minimalprofil", profileText: "Ihre Daten bleiben im Browser.", age: "Alter", height: "Größe", weight: "Gewicht", waist: "Taillenumfang", optional: "optional", movementTitle: "Aktivität und Sitzen", recoveryTitle: "Schlaf und Erholung", nutritionTitle: "Ernährung für Langlebigkeit", habitsTitle: "Allgemeine Gewohnheiten", vitalsTitle: "Optionale Gesundheitswerte", sportType: "Hauptsportart", moderateMinutes: "Moderate Minuten / Woche", vigorousMinutes: "Intensive Minuten / Woche", strengthSessions: "Krafttraining / Woche", mobilitySessions: "Mobilität / Woche", sittingHours: "Sitzstunden / Tag", sportYears: "Jahre regelmäßiger Praxis", socialPractice: "Soziale Ausübung", injuries: "Verletzungen oder Einschränkungen", sleepHours: "Schlaf / Nacht", sleepQuality: "Schlafqualität", stressLevel: "Empfundener Stress, 0 bis 10", fatigueLevel: "Müdigkeit, 0 bis 10", energyStability: "Energie tagsüber", emotionalEating: "Stressbedingtes Essverlangen", fruitVegServingsPerDay: "Obst und Gemüse / Tag", legumesPerWeek: "Hülsenfrüchte / Woche", wholeGrains: "Vollkorn", ultraProcessed: "Hochverarbeitete Lebensmittel", sugaryDrinksPerWeek: "Zuckergetränke / Woche", proteinAtMeals: "Protein zu Mahlzeiten", nutsSeedsPerWeek: "Nüsse und Samen / Woche", fattyFishPerWeek: "Fettreicher Fisch / Woche", processedMeatPerWeek: "Verarbeitetes Fleisch / Woche", appetiteChange: "Kürzlich verminderter Appetit", unintentionalWeightLoss: "Unbeabsichtigter Gewichtsverlust", tobacco: "Tabak oder Nikotin", alcoholDrinksPerWeek: "Alkoholische Getränke / Woche", systolic: "Systolischer Blutdruck", diastolic: "Diastolischer Blutdruck", restingHeartRate: "Ruhepuls", breakdownTitle: "Punktedetails", favorableTitle: "Günstige Faktoren", watchTitle: "Zu beobachtende Faktoren", noneReported: "Keine wesentlichen Signale bei den aktuellen Antworten.", methodTitle: "Methode und Grenzen", methodText: "Diese Schätzung basiert auf einem Verhaltensscore aus selbst angegebenen Lebensgewohnheiten. Sie misst keine Biomarker und ist keine medizinische Diagnose. Unbeabsichtigter Gewichtsverlust, ungewöhnliche Müdigkeit oder auffällige Werte sollten medizinisch abgeklärt werden.",
  componentActivity: "Körperliche Aktivität", componentSedentary: "Sitzzeit", componentSleep: "Schlaf", componentStressRecovery: "Stress und Müdigkeit", componentTobacco: "Tabak und Nikotin", componentAlcohol: "Alkohol", componentMorphology: "Körperzusammensetzung", componentVitals: "Gesundheitswerte", factorRegularActivity: "regelmäßige körperliche Aktivität", factorProtectiveNutrition: "schützende Ernährungsgewohnheiten", factorLowTobaccoExposure: "geringe Tabak- oder Nikotinexposition", factorHighSedentaryTime: "hohe Sitzzeit", factorTobaccoOrNicotine: "Tabak- oder Nikotinkonsum", factorPoorSleep: "zu wenig oder schlechter Schlaf", factorFrequentUltraProcessed: "häufige hochverarbeitete Lebensmittel", factorHighAlcohol: "hoher Alkoholkonsum", factorHighFatigue: "starke Müdigkeit", factorIntenseStress: "starker Stress", factorAppetiteOrWeightChange: "Appetit- oder Gewichtsänderung beobachten",
  prioritiesTab: "Langlebigkeits-Prioritäten", prioritiesTitle: "Ihre 3 wichtigsten Hebel", prioritiesIntro: "Personalisierte Rangfolge nach Zielabweichung, Bedeutung des Faktors und Ihren Antworten.", prioritiesEmpty: "Es zeigt sich keine starke Priorität. Festigen Sie Ihre Gewohnheiten weiter.", priorityImpact: "Potenzieller Einfluss", priorityAction: "Konkrete Maßnahme", priorityWhy: "Warum",
  priorityTobaccoTitle: "Tabak oder Nikotin reduzieren und beenden", priorityTobaccoAction: "Legen Sie ein Ausstiegsdatum fest und holen Sie medizinische oder pharmazeutische Unterstützung.", priorityTobaccoRationale: "Tabakexposition bleibt eine wichtige und veränderbare Ursache vorzeitiger Sterblichkeit.", priorityActivityTitle: "Körperliche Aktivität steigern", priorityActivityAction: "Steigern Sie sich auf 150–300 Minuten moderate Aktivität pro Woche plus zwei Krafteinheiten.", priorityActivityRationale: "Regelmäßige Aktivität unterstützt Herz-Kreislauf, Stoffwechsel, Muskeln und Kognition.", prioritySedentaryTitle: "Sitzzeit reduzieren", prioritySedentaryAction: "Unterbrechen Sie Sitzen alle 30–60 Minuten und ergänzen Sie kurze Spaziergänge.", prioritySedentaryRationale: "Lange Sitzzeiten bleiben auch bei sportlich aktiven Menschen ungünstig.", prioritySleepTitle: "Schlaf verbessern", prioritySleepAction: "Halten Sie regelmäßige Zeiten ein, zielen Sie auf 7–9 Stunden und lassen Sie anhaltende Schlafprobleme, Schnarchen oder Apnoe-Verdacht abklären.", prioritySleepRationale: "Schlaf beeinflusst Erholung, Stoffwechsel, Immunität und kognitive Funktionen.", priorityNutritionTitle: "Ernährungsqualität verbessern", priorityNutritionAction: "Mehr Gemüse, Obst, Hülsenfrüchte, Vollkorn, Nüsse und Fisch; weniger hochverarbeitete Produkte und verarbeitetes Fleisch.", priorityNutritionRationale: "Pflanzenreiche, wenig verarbeitete Ernährungsmuster sind mit besseren kardiometabolischen Ergebnissen verbunden.", priorityAlcoholTitle: "Alkohol reduzieren", priorityAlcoholAction: "Reduzieren Sie schrittweise die Menge und planen Sie mehrere alkoholfreie Tage pro Woche.", priorityAlcoholRationale: "Das Gesundheitsrisiko steigt mit der Menge; weniger ist meist besser.", priorityStressTitle: "Stress und Müdigkeit angehen", priorityStressAction: "Planen Sie tägliche Erholung, schützen Sie den Schlaf und holen Sie Hilfe bei anhaltender Erschöpfung.", priorityStressRationale: "Chronischer Stress und Müdigkeit können Gesundheitsverhalten und Lebensqualität verschlechtern.", priorityMorphologyTitle: "Stoffwechselgesundheit verbessern", priorityMorphologyAction: "Setzen Sie auf schrittweise Änderungen bei Ernährung, Aktivität und Kraft statt auf schnellen Gewichtsverlust.", priorityMorphologyRationale: "Körperzusammensetzung und Taillenumfang sind nützliche Marker des Stoffwechselrisikos.",
  supplementTitle: "Arkopharma Langlebigkeit 12", supplementIntro: "Produktinformation und Vorsicht — dieser Abschnitt empfiehlt keine routinemäßige Einnahme.", supplementComposition: "Wichtige Inhaltsstoffe", supplementCompositionText: "Chicorée-Fasern, Acerola, roter Ginseng, Ingwer, Quercetin, Ginkgo, Baikal-Helmkraut, Melonen-SOD, Vitamine C, B3, D3, E und A, Magnesium, Zink und Selen.", supplementEvidence: "Evidenzübersicht", supplementEvidenceText: "Vitamine und Mineralstoffe helfen vor allem bei unzureichender Zufuhr oder Mangel. Ein direkter lebensverlängernder Effekt der Gesamtformel beim Menschen ist nicht belegt.", supplementCaution: "Wichtige Vorsichtsmaßnahmen", supplementCautionText: "Nur für Erwachsene. Nicht in Schwangerschaft oder Stillzeit und bei Antikoagulanzien, Antidiabetika oder Antidepressiva nicht ohne fachlichen Rat verwenden. Andere Vitamin-D- und Vitamin-A-Quellen berücksichtigen.", supplementRule: "Ein Nahrungsergänzungsmittel ersetzt weder abwechslungsreiche Ernährung noch Bewegung, Schlaf oder medizinische Betreuung."
};

export const messages: Record<Language, Record<string, string>> = { fr, en, it, de };

export function translate(language: Language, key: string) {
  return messages[language][key] || messages.fr[key] || key;
}
